const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
let finish, requests=0, loading='';
const animations=[],listeners={};
const animate=(frames,options)=>{const animation={frames,options,cancel(){}};animations.push(animation);return animation};
const app={innerHTML:'',firstElementChild:{cloneNode:()=>({})},animate};
const layer=()=>({style:{},append(){},setAttribute(){},remove(){},animate});
const page={isConnected:true,querySelector:()=>loading||null,insertAdjacentHTML:(_,html)=>{loading=html}};
const context=vm.createContext({window:{scrollY:0,scrollTo(){},addEventListener:(name,fn)=>listeners[name]=fn},getComputedStyle:()=>({transform:'none'}),matchMedia:()=>({matches:false}),location:{hash:''},document:{createElement:layer,body:{append(){}},querySelector:selector=>selector==='#app'?app:page},history:{pushState(){}},navigator:{},setTimeout:callback=>{requests++;finish=callback}});
vm.runInContext(fs.readFileSync('app.js','utf8'),context);
(async()=>{
  const pending=vm.runInContext('toggleBill(0)',context);
  assert.match(loading,/loading\.gif.*数据请求中/);
  assert.equal(vm.runInContext('expanded',context),'current');
  await vm.runInContext('toggleBill(0)',context);
  assert.equal(requests,1);
  finish();await pending;
  assert.equal(vm.runInContext('expanded',context),'pending');
  assert(!app.innerHTML.includes('bill-loading-mask'));
  loading='';
  await vm.runInContext('toggleBill(0)',context);
  assert.equal(vm.runInContext('expanded',context),null);
  assert.equal(requests,1);
  const cancelled=vm.runInContext('toggleBill(1)',context);
  page.isConnected=false;finish();await cancelled;
  assert.equal(vm.runInContext('expanded',context),null);
  page.isConnected=true;
  const detail=vm.runInContext('showDetailObject(transactions.current[0])',context);
  assert(app.innerHTML.includes('交易详情'));
  assert(app.innerHTML.includes('加载中，请稍等'));
  assert(!app.innerHTML.includes('detail-main'));
  finish();await detail;
  assert(app.innerHTML.includes('detail-main'));
  assert(!app.innerHTML.includes('加载中，请稍等'));
  const abandoned=vm.runInContext('showDetailObject(transactions.current[0])',context);
  page.isConnected=false;
  vm.runInContext('renderBills()',context);
  finish();await abandoned;
  assert(app.innerHTML.includes('bills-page'));
  assert(!app.innerHTML.includes('detail-main'));
  vm.runInContext('openSearch()',context);
  assert.equal(animations.at(-1).frames[0].transform,'translateX(100%)');
  assert.equal(animations.at(-1).frames[1].transform,'translateX(0)');
  context.location.hash='';
  listeners.popstate({state:null});
  assert.equal(animations.at(-1).frames[1].transform,'translateX(100%)');
  assert(app.innerHTML.includes('bills-page'));
  console.log('Verified forward/backward navigation directions.');
  console.log('Verified bill/detail loading, duplicate-click guard, expansion, immediate collapse and navigation cancellation.');
})().catch(error=>{console.error(error);process.exitCode=1});
