const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('app.js','utf8');
assert.match(source,/onfocus="clearSearchResults\(\)"/);
assert.match(source,/list\.style\.minHeight=`\$\{list\.offsetHeight\}px`/);
assert.match(source,/showLoading\(page,false\)[\s\S]*setTimeout\(resolve,400\)/);
assert.match(fs.readFileSync('style.css','utf8'),/\.mask\{touch-action:none;overscroll-behavior:contain\}/);
assert.match(fs.readFileSync('style.css','utf8'),/\.search-box input\{-webkit-appearance:none;appearance:none;background:transparent/);
let finish, requests=0, loading='', delays=[];
const animations=[],listeners={};
const animate=(frames,options)=>{const animation={frames,options,cancel(){}};animations.push(animation);return animation};
const app={innerHTML:'',firstElementChild:{cloneNode:()=>({})},animate};
const layer=()=>({style:{},append(){},setAttribute(){},remove(){},animate});
const page={isConnected:true,classList:{toggle(){},remove(){}},addEventListener(){},querySelector:selector=>selector==='.bill-loading-mask'&&loading?{remove:()=>loading=''}:selector==='.info-modal-mask'&&loading.includes('info-modal-mask')?{remove:()=>loading=''}:loading||null,insertAdjacentHTML:(_,html)=>{loading=html}};
let backRequests=0;
const context=vm.createContext({window:{scrollY:0,scrollTo(){},addEventListener:(name,fn)=>listeners[name]=fn},getComputedStyle:()=>({transform:'none'}),matchMedia:()=>({matches:false}),location:{hash:''},document:{createElement:layer,body:{append(){}},querySelector:selector=>selector==='#app'?app:selector==='.info-modal-mask'&&loading.includes('info-modal-mask')?{remove:()=>loading=''}:page},history:{pushState(){},back(){backRequests++}},navigator:{},setTimeout:(callback,delay)=>{requests++;delays.push(delay);finish=callback}});
vm.runInContext(source,context);
assert.equal(vm.runInContext("amountClass({amount:'¥ -1.00'})",context),'negative');
assert.equal(vm.runInContext("amountClass({amount:'¥ 1.00'})",context),'');
(async()=>{
  const pending=vm.runInContext('toggleBill(0)',context);
  assert.match(loading,/loading\.gif.*数据请求中/);
  assert.equal(vm.runInContext('expanded',context),null);
  await vm.runInContext('toggleBill(0)',context);
  assert.equal(requests,1);
  finish();await pending;
  assert.equal(vm.runInContext('expanded',context),'pending');
  assert(!app.innerHTML.includes('bill-loading-mask'));
  loading='';
  await vm.runInContext('toggleBill(0)',context);
  assert.equal(vm.runInContext('expanded',context),null);
  assert.equal(requests,1);
  const cancelled=vm.runInContext('toggleBill(1)',context);
  page.isConnected=false;finish();await cancelled;
  assert.equal(vm.runInContext('expanded',context),null);
  page.isConnected=true;
  const detail=vm.runInContext('showDetailObject(transactions.current[0])',context);
  assert(app.innerHTML.includes('交易详情'));
  assert(app.innerHTML.includes('加载中，请稍等'));
  assert(!app.innerHTML.includes('detail-main'));
  finish();await detail;
  assert(app.innerHTML.includes('detail-main'));
  assert(!app.innerHTML.includes('加载中，请稍等'));
  const abandoned=vm.runInContext('showDetailObject(transactions.current[0])',context);
  page.isConnected=false;
  vm.runInContext('renderBills()',context);
  finish();await abandoned;
  assert(app.innerHTML.includes('bills-page'));
  assert(!app.innerHTML.includes('detail-main'));
  page.isConnected=true;
  loading='';
  const searchRequests=requests;
  const search=vm.runInContext('openSearch()',context);
  assert(app.innerHTML.includes('查找交易'));
  assert(!app.innerHTML.includes('search-tools'));
  assert.match(loading,/loading\.gif.*数据请求中/);
  assert.equal(requests,searchRequests+1);
  assert.equal(delays.at(-1),600);
  finish();await search;
  assert(app.innerHTML.includes('search-tools'));
  assert.equal(animations.at(-1).frames[0].transform,'translateX(100%)');
  assert.equal(animations.at(-1).frames[1].transform,'translateX(0)');
  context.location.hash='';
  listeners.popstate({state:null});
  assert.equal(animations.at(-1).frames[1].transform,'translateX(100%)');
  assert(app.innerHTML.includes('home-page'));
  page.isConnected=true;
  vm.runInContext("billAccount='usd';expanded='current';renderBills()",context);
  assert(app.innerHTML.includes('账单金额说明'));
  assert(app.innerHTML.includes('openBillAmountInfo(1)'));
  assert(app.innerHTML.includes('该月无账单明细哦'));
  assert(app.innerHTML.includes('$ 0.00'));
  const dollarInfo=vm.runInContext('billAmountDetails(1)',context);
  assert.equal((dollarInfo.match(/\$ 0\.00/g)||[]).length,6);
  vm.runInContext("billAccount='cny';expanded=null;renderBills()",context);
  const amountInfo=vm.runInContext('billAmountDetails(bills.findIndex(b=>b.id==="current"))',context);
  const currentBill=vm.runInContext('bills.find(b=>b.id==="current")',context);
  const previousBill=vm.runInContext('bills.slice(bills.findIndex(b=>b.id==="current")+1).find(b=>b.amount)',context);
  assert(amountInfo.includes(`本期消费金额</span><b>${currentBill.amount}`));
  assert(amountInfo.includes(`上期账单金额</span><b>+${previousBill.amount}`));
  assert(amountInfo.includes(`上期还款</span><b>−${previousBill.amount}`));
  assert.match(amountInfo,/本期调整[\s\S]*−¥ 0\.00[\s\S]*循环利息[\s\S]*\+¥ 0\.00/);
  vm.runInContext("expanded='current';renderBills()",context);
  assert(app.innerHTML.includes('bill-amount-info'));
  assert.match(app.innerHTML,/bill-amount-info[^>]*"><img[^>]*empty-bill-icon[^>]*>账单金额说明/);
  vm.runInContext('renderBills()',context);
  const repayment=vm.runInContext('openRepayment()',context);
  assert(app.innerHTML.includes('信用卡还款'));
  assert.match(loading,/loading\.gif.*数据请求中/);
  finish();await repayment;
  assert(app.innerHTML.includes('repayment-card'));
  const repayButton={disabled:true};
  context.repayButton=repayButton;
  vm.runInContext("updateRepaymentButton({value:'100',closest:()=>({querySelector:()=>repayButton})})",context);
  assert.equal(repayButton.disabled,false);
  vm.runInContext("updateRepaymentButton({value:'',closest:()=>({querySelector:()=>repayButton})})",context);
  assert.equal(repayButton.disabled,true);
  const installment=vm.runInContext('openInstallment()',context);
  assert(app.innerHTML.includes('分期还款'));
  assert.match(loading,/loading\.gif.*数据请求中/);
  finish();await installment;
  assert(loading.includes('可办理分期金额不足'));
  context.location.hash='#installment';
  vm.runInContext('closeInstallmentNotice()',context);
  assert.equal(backRequests,1);
  console.log('Verified forward/backward navigation directions.');
  console.log('Verified bill/detail loading, duplicate-click guard, expansion, immediate collapse and navigation cancellation.');
})().catch(error=>{console.error(error);process.exitCode=1});
